# Limit Order Configuration
# Generated by bot order updater

ORDER_CONFIG = {
    "use_limit_orders": True,
    "post_only": True,  # Maker fees only (0.02% vs 0.04%)
    "max_retries": 3,
    "retry_wait_time": 5,  # seconds
    "price_adjustment": {
        "buy": 1.0001,  # Slightly above ask for better fill
        "sell": 0.9999  # Slightly below bid for better fill
    },
    "stop_loss": {
        "use_market_order": True  # Keep market orders for stop-loss
    },
    "expected_fill_rate": 0.90,  # Monitor if below this
    "max_spread_threshold": 0.001  # 0.1% max spread to trade
}

# Expected improvements:
# - Slippage reduction: ~90%
# - Fee reduction: ~50% (maker vs taker fees)
# - Previous slippage: 0.15-0.178 USDT per trade
# - New slippage: 0 USDT (limit orders at exact price)
